spring:
  application:
    name: Hot Spring

file-processor-config:
  s3:
    accessKey: <access-key>
      secretKey: <secret-key>
      region: <region>
      bucket: <bucket-name>
      s3Retrieved: src/main/resources/file/s3Retrieved

  crypto:
    keypair-config:
      private-key-path: src/main/resources/crypto/private.dat
      public-key-path: src/main/resources/crypto/public.dat
      username: test
      password: test
      isArmored: True
      keySize: 1024
    file-config:
      input-file-location: src/main/resources/file/plain
      zipped-file-location: src/main/resources/file/zipped
      ciphered-file-location: src/main/resources/file/ciphered
      deciphered-file-location: src/main/resources/file/deciphered
      s3-retrieved-file-location: src/main/resources/file/s3Retrieved
      unzipped-file-location: src/main/resources/file/unzipped
